### PR TITLE
add email of the customer when creating one

### PR DESCRIPTION
**Pull request by dizda**
Hey guys, thanks for the lib!

I think this would be useful to also store the email of the customer when creating one with a token (so the payment method has been provided by the user).

That's it!
Cheers.

### CODE REVIEW

**Comment by barryvdh** [comment]
Shouldn't you get that from the Card object?

**Comment by dizda** [comment]
Hey thanks for reviewing this PR.

FYI, I use the "Stripe Checkout" form, which provides me a token to use when the user has filled the form. 
I don't use the card form.

**Comment by delatbabel** [comment]
To answer both the OP and @barryvdh I believe that some past changes in the Stripe API have moved away from CreateCustomer requiring (or even using) a card object, and instead CreateCustomer now just uses an email address.  So I believe that the methodology behind this PR is correct.

Please give me another day or so to do some testing and review the code before I merge this.  I want to make sure that it works for all Stripe accounts.

**Comment by dizda** [comment]
Sure @delatbabel, no problem!

**Comment by delatbabel** [comment]
Merged. Please test this in production and let me know if it works. If so then I will tag for release.

**Comment by dizda** [comment]
Thanks @delatbabel ! FYI my shop is not live yet, so couldn't tell you except with the "sandbox" mode.

**Comment by delatbabel** [comment]
OK once you are live and can verify that it works with production keys then comment here and I will tag for release.

**Comment by dizda** [comment]
👍

**Comment by dizda** [comment]
@delatbabel All good in live env!

**Comment by delatbabel** [comment]
Tagged in v2.4.2

**Comment by dizda** [comment]
Thanks fellas!

**Pull request merged**
