### PR TITLE
Fixed createToken request. Card data is now sent to Stripe API.

### LINKED ISSUE #92: CreateToken request does not send card data to API
This is a followup to my comments on #88

### PR DESCRIPTION
**Pull request by nathanjosiah**
Fixes #92

### CODE REVIEW

**Comment by nathanjosiah** [comment]
I'm not sure why the PHP 5.3 build is failing. The error seems to be for an internal Travis error.

**Comment by delatbabel** [comment]
You can remove version 5.3 from the .travis.yml -- we're no longer requiring support for that.  Hopefully that will fix the CI issue.

**Comment by delatbabel** [comment]
HHVM support is no longer required either so in case that's there then remove it as well.

**Comment by nathanjosiah** [comment]
@delatbabel I updated the travis config and now everything builds fine.

**Pull request merged**
