### PR TITLE
Fix source / card reference issue.

### PR DESCRIPTION
**Pull request by RyanThompson**
Response data returns default_source.

Since you have to have a customer for stripe to save a card, the ID is the customer reference. Not the card. default_card is no where to be found. It's referred to as default_source only.

This is all dummy data:

Parameters:

```
array (
  'card' => 
  array (
    'firstName' => 'Ryan',
    'lastName' => 'Thompson',
    'type' => 'visa',
    'cvv' => '123',
    'expiryMonth' => '10',
    'expiryYear' => '2020',
    'number' => '4242',
  ),
)
```

Response:

```
array (
  'id' => 'cus_8rWBNeWBtjRN6A',
  'object' => 'customer',
  'account_balance' => 0,
  'created' => 1469130489,
  'currency' => NULL,
  'default_source' => 'card_18Zn9REFKcfqUcivNPn9G3MC',
  'delinquent' => false,
  'description' => NULL,
  'discount' => NULL,
  'email' => NULL,
  'livemode' => false,
  'metadata' => 
  array (
  ),
  'shipping' => NULL,
  'sources' => 
  array (
    'object' => 'list',
    'data' => 
    array (
      0 => 
      array (
        'id' => 'card_18Zn9REFKcfqUcivNPn9G3MC',
        'object' => 'card',
        'address_city' => '',
        'address_country' => '',
        'address_line1' => '',
        'address_line1_check' => NULL,
        'address_line2' => '',
        'address_state' => '',
        'address_zip' => '',
        'address_zip_check' => NULL,
        'brand' => 'Visa',
        'country' => 'US',
        'customer' => 'cus_8rWBNeWBtjRN6A',
        'cvc_check' => 'pass',
        'dynamic_last4' => NULL,
        'exp_month' => 10,
        'exp_year' => 2020,
        'fingerprint' => 'ZD9wsf1rHJ6Y0PMb',
        'funding' => 'credit',
        'last4' => '4242',
        'metadata' => 
        array (
        ),
        'name' => 'Ryan Thompson',
        'tokenization_method' => NULL,
      ),
    ),
    'has_more' => false,
    'total_count' => 1,
    'url' => '/v1/customers/cus_8rWBNeWBtjRN6A/sources',
  ),
  'subscriptions' => 
  array (
    'object' => 'list',
    'data' => 
    array (
    ),
    'has_more' => false,
    'total_count' => 0,
    'url' => '/v1/customers/cus_8rWBNeWBtjRN6A/subscriptions',
  ),
)
```

### CODE REVIEW

**Comment by cfreear** [comment]
I would advise against merging this on any 2.x release as this would be a breaking change for users on Stripe API versions prior to [2015-02-18](https://stripe.com/docs/upgrades#2015-02-18) when ``default_card`` was changed to ``default_source``.

**Comment by delatbabel** [comment]
Well Travis is failing and there are objections to merge (and it's breaking BC).  Can the OP fix the BC issues somehow? Otherwise I will close this.

**Comment by RyanThompson** [comment]
I don't see so much as even a develop branch to put this under. If someone can let me know what they'd like done I will happily oblige.

What do you think about supporting both? If `default_source` is not found then check `default_card` and proceed like normal thereafter?

I would suggest keeping this open though. I am a little surprised this hasn't been fixed yet? It's over a year old if I understand correctly?

Cheers!

**Comment by delatbabel** [comment]
> If someone can let me know what they'd like done I will happily oblige.

* Fix the code so that the Travis tests pass.  See the Travis CI build details below.
* Don't break BC.

> What do you think about supporting both? If default_source is not found then check default_card and proceed like normal thereafter?

Yes, that would work.

**Comment by cfreear** [comment]
@RyanThompson The Stripe API update happened over a year ago however when using Stripe your version is set when you first make a call to them so ``default_card`` is still a valid Stripe response attribute that will be present for a lot of users and hasn't been deprecated.

**Comment by caicedodavid** [comment]
Hello, when will this update be available? Thank you for you answer in advance.

**Comment by delatbabel** [comment]
It will be available when someone fixes the code. I can't merge broken code, sorry.

**Comment by RyanThompson** [comment]
I will try and get to this today. As someone with my own very large project it's hard to find time - it would be great if the package owner or other capable contributor could follow up on this :-/

**Comment by sudiptpa** [comment]
@RyanThompson i have created a PR https://github.com/thephpleague/omnipay-stripe/pull/65 , please have a look if it works for you.

**Comment by delatbabel** [comment]
OK so I'm assuming that this is no longer required -- based on #65.  Please re-open if I'm incorrect.

**Pull request closed without merging**
