### PR TITLE
Added FetchTokenRequest

### PR DESCRIPTION
**Pull request by ruudk**
Added `fetchToken` method and changed the HTTP Method for `fetchTransaction` from `POST` to `GET`

### CODE REVIEW

**Comment by ruudk** [comment]
@adrianmacneil Could this be merged :)?

**Comment by cfreear** [comment]
I think @kayladnls is maintaining most/all Omnipay repositories now.

**Comment by adrianmacneil** [comment]
:+1: it looks good to me

I'll merge it, but let @kayladnls publish a new version when ready

**Comment by kayladnls** [comment]
Thanks @adrianmacneil 

@ruudk this has been included in v2.1.2 :+1:

**Pull request merged**
