### PR TITLE
Added support for balance transaction

### PR DESCRIPTION
**Pull request by laoneo**
To get balance details like the net amount or the fee, Stripe has a [balance endpoint](https://stripe.com/docs/api/curl#balance). This pull request adds the necessary functions to get a balance of a transaction. The endpoint is described here https://stripe.com/docs/api/curl#retrieve_balance_transaction.

### CODE REVIEW

**Comment by BrunoDeBarros** [comment]
I'd love to see this one merged; it's super useful.

**Comment by laoneo** [comment]
Me too, but honestly omnipay doesn't has much traffic in the last couple of months, so the chance is little it get's merged. At least I could configure composer the way that it would accept it from my forked repo :-)

**Comment by BrunoDeBarros** [comment]
That's what I did; your changes are working perfectly! Thank you so much for doing this.

**Comment by laoneo** [comment]
Just as reference for the next visitor of that PR, that should work in composer:

	{
		"require" : {
			"omnipay/stripe": "dev-balance-support"
		},
		"repositories": [
			{
				"type": "vcs",
				"url": "https://github.com/Digital-Peak/omnipay-stripe"
			}
		]
	}

**Pull request merged**
