### PR TITLE
FIX: error message/code may not always be set (fixes #62)

### LINKED ISSUE #62: PHP notice error: undefined index `code` on Message/Response.php#L308
Hi there,

I'm getting this error in the context of the Craft Commerce Plugin, on the last step of checkout.

The data I feed to the form is correct (a valid Stripe token), and it works fine with the Test API Keys. So the error only happens when working with the Live Keys.

https://github.com/thephpleague/omnipay-stripe/blob/master/src/Message/Response.php#L308

Here's an example of the data I get using Stripe.js (I'm "blurring" the token because real card)

```js
{
  id: "tok_19J5meHOW6ChjHQ7djwPxxxx",
  object: "token",
  card: Object,
  client_ip: "83.32.118.217",
  created: 1479926872,
  livemode: true,
  type: "card",
  used: false
}
```

Any ideas?

Please let me know If I should be asking somewhere else.

Thank you!

### PR DESCRIPTION
**Pull request by kinglozzer**

### CODE REVIEW

**Comment by delatbabel** [comment]
Thanks for the PR.  Test and everything, great work.  Please confirm that this works (does not break anything else) in production and I will tag for release.

**Comment by kinglozzer** [comment]
@delatbabel I don’t have a production site running Stripe currently, only a site still running in test mode, but everything is working as expected now (successful payments, and failed payments using Stripe’s test cards). Perhaps @acstll has a live site to confirm on?

**Comment by acstll** [comment]
Yes, I have a live site to test on. I will try to do it today and let you know (got lots of work). (Thanks for the PR @kinglozzer)

**Comment by acstll** [comment]
I tested this patch and got no errors but some very weird behaviour:

the transaction shows OK (completed and succesful) in Craft Commerce, but there's no signs of it in Stripe, no money.

I tested again with the current code and got the original error #62 

For the record, I tested placing an order for a product of less than 0,50€ (which gets rejected by Stripe with an `invalid_request_error` type of error).

I'm pinging @lukeholder (I think he could help).

I would suggest more testing before releasing this patch.

**Comment by lukeholder** [comment]
If stripe doesn't allow a payment for 50c or less should we add this to the validation around here?: https://github.com/thephpleague/omnipay-stripe/blob/master/src/Message/AuthorizeRequest.php#L170

**Comment by kinglozzer** [comment]
Perhaps Craft Commerce is checking for the presence of an error message, or error code, instead of checking `isSuccessful()`? I can’t see why else this patch would affect how payments are received

**Comment by lukeholder** [comment]
Only checking isSuccessful, try a transaction for less than 50c. 

Ah, could it possibly be raising an exception rather than a isSuccess false?

**Comment by kinglozzer** [comment]
Sorry, I’d forgotten about this. I’ve been running this code in production for a few weeks now with no issues.

**Pull request merged**
