### PR TITLE
Allow skipping billing details if creating payment method with token.

### PR DESCRIPTION
**Pull request by andris-sevcenko**
Also, fix a bug where creating a payment method was not possible at all.

### CODE REVIEW

**Comment by andris-sevcenko** [comment]
@m2de see if this is related to the issues you were having.

Also, fun fact, 3DS 2.0 using `manual` confirmation flow was not working on Stripe test environment for sure yesterday. Might have gone way back to last Thursday when I last checked, so if one of the issues you had were "Huh, the card just gets declined instead of returning a redirect to 3DS authentication page", then that was that.

**Comment by m2de** [comment]
Thanks @andris-sevcenko . I am still trying to make things work (although not had a huge amount of time on it). The other issue I ran into that older versions of Stripe return `requires_source_action` instead of `requires_action`. So this package wouldn't recognise the redirect being required. Was going to open a PR for it when I got things working.

**Comment by andris-sevcenko** [comment]
@m2de yeah that issue is related to the Stripe API version you're using. I have no idea if specifying that version is something that Omnipay should be doing or not.

**Comment by m2de** [comment]
It's not something Omnipay (or the codebase) has control over. It is an upgrade required to be actioned within the Stripe UI. 

Screenshot 2019-07-23 at 09 08 00

But the package can simply check for both strings to support both API versions.

**Comment by andris-sevcenko** [comment]
Well, you can specify the API version for each request (https://stripe.com/docs/api/versioning?lang=curl)

**Comment by m2de** [comment]
> Well, you can specify the API version for each request (https://stripe.com/docs/api/versioning?lang=curl)

That is very useful info, thanks.

**Pull request merged**
