### PR TITLE
Support: FetchChargeRequest

### PR DESCRIPTION
**Pull request by WellingGuzman**
Also fixed wrong method used to check if email was set.

### CODE REVIEW

**Comment by delatbabel** [comment]
Merged. Please confirm whether this works in production then I will tag.

**Comment by WellingGuzman** [comment]
@delatbabel we are using it in production right now, no complain. :)

Thanks!

**Comment by cfreear** [comment]
Bit late to this but could you (@WellingGuzman) explain the difference between this new [FetchChargeRequest](https://github.com/thephpleague/omnipay-stripe/blob/master/src/Message/FetchChargeRequest.php) and the old [FetchTransactionRequest](https://github.com/thephpleague/omnipay-stripe/blob/master/src/Message/FetchTransactionRequest.php)?

**Comment by WellingGuzman** [comment]
@cfreear whoa this is awkward, there's none, there are the same thing, I was looking for a charge requests so I made a PR. this should be remove out of the repo and I should be using `FetchTransactionRequest` instead.

Sorry for the confusion.

cc. @delatbabel

**Comment by cfreear** [comment]
@WellingGuzman Haha, no worries, from looking at the code I thought it was the same but it's been a while since I've used the Stripe API so wasn't sure!

**Comment by delatbabel** [comment]
OK should I revert this? Will it break things for you @WellingGuzman ?

**Comment by cfreear** [comment]
@delatbabel it might be best to leave this in and remove it for v3. I know it's only been in for less than a month but removing it is still a potential bc for users of v2.3.3

**Comment by delatbabel** [comment]
Noted, will do. Someone might drop in a PR with a @deprecated notice or something similar.

**Comment by WellingGuzman** [comment]
I missed all these messages, @delatbabel unfortunately it will break things for me, I will have to switch methods.

I will update my code. I will let you all know. (if necessary)

**Comment by cfreear** [comment]
@WellingGuzman ``fetchCharge`` has been deprecated via #50 and is only due for removal in v3 so as long as you don't update to v3 your code will be fine.

**Comment by WellingGuzman** [comment]
@cfreear thank you so much, and sorry for confusion.

**Pull request merged**
