### PR TITLE
Updated with tests and fixed class paths

### PR DESCRIPTION
**Pull request by bmeclazcke**
Fixed paths since I forgot they were relative to my app in development
Also included tests
Thanks!

### CODE REVIEW

**Comment by delatbabel** [comment]
There's a syntax error in your testSendFailure() function, you'll need to fix that before I can merge.

**Comment by jsampedro77** [comment]
Version 2.4.3 is broken because of this namespace error. 
@bmeclazcke will you provide the fixed test so it can be merged and fix that error?

@delatbabel wouldn't it be better to have a broken test than a broken code? I mean, right now 2.4.3 it causing an exception when trying to use that listPlans() method.

**Comment by bmeclazcke** [comment]
Sorry ppl! Never really had the time to run this. There I pushed I new pull request.

**Comment by delatbabel** [comment]
This was superseded by #71

**Comment by delatbabel** [comment]
Ah, no it's not because that was aborted.  I'll try a manual fix.

**Pull request merged**
