### PR TITLE
Add subscriptions and event support

### PR DESCRIPTION
**Pull request by WellingGuzman**
This will add support to Create and Cancel Customer Subscriptions.

### CODE REVIEW

**Comment by delatbabel** [comment]
Is it not the case that these message classes depend on at least a CreatePlan message? Otherwise how do you obtain a plan ID to send as part of the CreateSubscription request?

**Comment by WellingGuzman** [comment]
@delatbabel you're right, as this was the first message I made I wanted to make a PR. And I didn't realize this until you say it, I'm using Guzzle to make request and creating and retrieving the plans.

I have more contributions to stripe. I'll made this Guzzle into omnipay request.

Thanks for letting me know.

**Comment by delatbabel** [comment]
OK I'm going to hold on this until you have createPlan and deletePlan at least implemented (along with test cases). The PayPal_Rest gateway in omnipay-paypal implements something similar, you might want to take a look at that.

Some usage examples in the class header docblocks might be useful as well.

**Comment by WellingGuzman** [comment]
I'm still creating the request while I'm needing it, eventually I'd create the createPlan and deletePlan.

**Comment by delatbabel** [comment]
Is this reasonably complete and ready for merge yet? Including test coverage? If not then let me know when that happens.

**Comment by WellingGuzman** [comment]
I think this is reasonably complete, there's still some things missing at some point, such as parameters for limit results and ability to handle `metadata` parameter. but it includes test coverage.

I've been using it with no problem so far.

**Comment by delatbabel** [comment]
Hi,
I need some additional test coverage on the gateway methods that you added please.
testcoverage

**Comment by WellingGuzman** [comment]
@delatbabel oh right, I will do that later, I forgot about that.

On a side note, which software/service did you use to get that info? I will like to know.

Thanks!

**Comment by delatbabel** [comment]
./runtests.sh in the root directory runs the tests via phpUnit. I then just loaded the output into my browser and took a screen shot.

**Comment by delatbabel** [comment]
I have merged this now but not tagged it. I will leave it to you to confirm that it's all working in production, and if you can confirm that then I'll tag it for release.

**Comment by WellingGuzman** [comment]
I've been working with the new changes, and we are still working on development stage, so far there has not been any issue. If something shows up I will let you know.

**Pull request merged**
