### PR TITLE
Don't include CVV if it's empty

### LINKED ISSUE #14: Don't include CVV if it's empty
Stripe doesn't requre CVV (for instance, for recurring transactions).
But if it's set, it's required to be non-empty.

### PR DESCRIPTION
**Pull request by evgenius**
Fixes #14

### CODE REVIEW

**Comment by kayladnls** [comment]
Can you add a test to cover this please? Thank you!

**Comment by delatbabel** [comment]
I updated #13 to include this and also added some tests.

**Comment by delatbabel** [comment]
This can be closed now because it's already incorporated into #13 which has already been merged.

**Comment by delatbabel** [comment]
This can be closed.

**Pull request closed without merging**
