### PR TITLE
Make sure Curl uses TLS >= v1.2. Fixes #53.

### LINKED ISSUE #53: Driver no longer works for new Stripe accounts where TLS 1.0 enabled on server
When trying to process payments for new Stripe accounts, we now receive the error:

> Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later. You can learn more about this at https://stripe.com/blog/upgrading-tls.

### PR DESCRIPTION
**Pull request by coatesap**

### CODE REVIEW

**Comment by delatbabel** [comment]
Merged. Can you confirm that this works in production, then if so I will tag for release.

**Comment by coatesap** [comment]
Hi @delatbabel - yes, it's working perfectly now.

**Comment by gmoreira** [comment]
Were these the changes required as per the https://stripe.com/blog/upgrading-tls upgrade?

**Comment by coatesap** [comment]
@gmoreira - yes, that's correct.

**Comment by gmoreira** [comment]
Thanks for clarifying @coatesap

**Comment by coatesap** [comment]
@delatbabel - could you tag a new release, so we can close down our fork of the repo?

**Comment by barryvdh** [comment]
Tagged 2.4.0

**Pull request merged**
