### PR TITLE
Enabling token request gateway

### PR DESCRIPTION
**Pull request by pedro-stanaka**
Hello @delatbabel, I've tested my last PR on production and it worked all right, but I had to make modifications in the Gateway for them to work. This PR contain these modifications that make the `CreateToken` request work. 

Please merge this when you can, and let me know if there is something to be improved.

Thanks for the acceptance of the last PR BTW.

### CODE REVIEW

**Comment by pedro-stanaka** [comment]
Hello, any news here? Sorry for the bothering, I know it is not easy to keep a repo like this one, but I have people breathing down my neck because of this :slightly_smiling_face:. If you guys could merge this I would be very happy. Thanks!

**Comment by delatbabel** [comment]
OK, I have merged this. Can you please confirm that it works in production and I will tag for release.

**Comment by pedro-stanaka** [comment]
This is working on production. Sorry for the late notice!

**Comment by nathanjosiah** [comment]
@pedro-stanaka @delatbabel The createToken request does not work as is. Tracing through the code, the issue appears to be that the CreditCard object set on the request is never converted back to an array before sent to the Stripe API and as a result, there is no way to use the createToken method without manually overriding a bunch of things using Reflection. Can you take a look at that?

**Comment by nathanjosiah** [comment]
@pedro-stanaka @delatbabel Looking further, the test for the createToken request data is actually failing but wasn't obvious because the test function wasn't prefixed with "test" and therefore not run. I will attempt to fix and submit a PR.

**Pull request merged**
